[tool.black]
extend-exclude = '''
/migrations/
'''

[tool.ruff]
target-version = "py312"
line-length = 100
extend-exclude = [
    "migrations",
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"config/settings.py" = ["E402"]
